### ISSUE TITLE
Bug with Electron 78

### ISSUE THREAD

**Issue by jevillard** [jakedowns/CypressHelpers#2]
Hi, 

It's a real good work :) but it's not work with Electron 78...

I have this error `TypeError: Cannot read property 'body' of undefined` because 

```js
error-utils.ts:14 Uncaught (in promise) Error: Invalid guestId: 12
    at electron/js2c/browser_init.js:5467:13
    at callHandler (electron/js2c/browser_init.js:5743:30)
    at EventEmitter.<anonymous> (electron/js2c/browser_init.js:5752:9)
    at EventEmitter.emit (events.js:203:13)
    at WebContents.<anonymous> (electron/js2c/browser_init.js:3834:23)
    at WebContents.emit (events.js:203:13)
```
Do you have an idea? Thanks

**Comment by jakedowns** [comment]
hey there, sorry for the delayed response.

i looked into this and adding electron support should be possible

let me know if it'd be useful to you still and i can look into adding it
